#each route describes how an incoming URL will be processed by Platform.sh

"https://{default}/":
  type: upstream
  upstream: "ll_project:http"

"https://{default}/":
  type: redirect
  to: "https://{default}"